/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-05 21:33:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Abbah.Ahmed.*;

public final class AdminPanel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("Abbah.Ahmed");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>Interpreter</title>\r\n");
      out.write("	<!-- Include Bootstrap CSS -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- Include SweetAlert CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/sweetalert2@11.0.17/dist/sweetalert2.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Include SweetAlert JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11.0.17/dist/sweetalert2.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<style>\r\n");
      out.write("  /* Style the form input */\r\n");
      out.write("  #interpreter-form input[type=\"text\"] {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 12px 20px;\r\n");
      out.write("    margin: 8px 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    border: 2px solid #ccc;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    background-color: #f8f8f8;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  /* Style the form button */\r\n");
      out.write("  #interpreter-form button[type=\"submit\"] {\r\n");
      out.write("    background-color: #4CAF50;\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 12px 20px;\r\n");
      out.write("    margin: 8px 0;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  /* Change the button color on hover */\r\n");
      out.write("  #interpreter-form button[type=\"submit\"]:hover {\r\n");
      out.write("    background-color: #45a049;\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/* Color of the links BEFORE scroll */\r\n");
      out.write(".navbar-scroll .nav-link,\r\n");
      out.write(".navbar-scroll .navbar-toggler-icon,\r\n");
      out.write(".navbar-scroll .navbar-brand {\r\n");
      out.write("  color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Color of the links AFTER scroll */\r\n");
      out.write(".navbar-scrolled .nav-link,\r\n");
      out.write(".navbar-scrolled .navbar-toggler-icon,\r\n");
      out.write(".navbar-scrolled .navbar-brand {\r\n");
      out.write("  color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Color of the navbar AFTER scroll */\r\n");
      out.write(".navbar-scroll,\r\n");
      out.write(".navbar-scrolled {\r\n");
      out.write("  background-color: #cbbcb1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mask-custom {\r\n");
      out.write("  backdrop-filter: blur(5px);\r\n");
      out.write("  background-color: rgba(255, 255, 255, .15);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-brand {\r\n");
      out.write("  font-size: 1.75rem;\r\n");
      out.write("  letter-spacing: 3px;\r\n");
      out.write("}\r\n");
      out.write("#InterpreterDiv {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 100px;\r\n");
      out.write("  left: 200px;\r\n");
      out.write("  background-color: white;\r\n");
      out.write("  opacity: 0.9;\r\n");
      out.write("  border-radius: 10px; /* adds rounded corners */\r\n");
      out.write("  box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.3); /* adds a subtle shadow */\r\n");
      out.write("  padding: 20px; /* adds padding inside the div */\r\n");
      out.write("}\r\n");
      out.write("#result {\r\n");
      out.write("  background-color: #333;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  font-family: 'Courier New', Courier, monospace;\r\n");
      out.write("  overflow-y: scroll;\r\n");
      out.write("	opacity:100%;\r\n");
      out.write("  height: 200px;\r\n");
      out.write("  border-radius:5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("  <!-- Navbar -->\r\n");
      out.write("  <nav class=\"navbar navbar-expand-lg navbar-light fixed-top mask-custom shadow-0\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"#!\"><span style=\"color: #5e9693;\">Library</span><span style=\"color: #fff;\">WebApp</span></a>\r\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-mdb-toggle=\"collapse\"\r\n");
      out.write("        data-mdb-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("        aria-label=\"Toggle navigation\">\r\n");
      out.write("        <i class=\"fas fa-bars\"></i>\r\n");
      out.write("      </button>\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("        <ul class=\"navbar-nav me-auto\">\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"#!\">Log Out</a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul class=\"navbar-nav d-flex flex-row\">\r\n");
      out.write("          <li class=\"nav-item me-3 me-lg-0\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"#!\">\r\n");
      out.write("              <i class=\"fas fa-shopping-cart\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item me-3 me-lg-0\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"#!\">\r\n");
      out.write("              <i class=\"fab fa-twitter\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item me-3 me-lg-0\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"#!\">\r\n");
      out.write("              <i class=\"fab fa-instagram\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <!-- Navbar -->\r\n");
      out.write("\r\n");
      out.write("  <!--Section: Design Block-->\r\n");
      out.write("  <section>\r\n");
      out.write("    <!-- Intro -->\r\n");
      out.write("    <div id=\"intro\" class=\"bg-image vh-100\" style=\"\r\n");
      out.write("          background-image: url('books.jpg');\r\n");
      out.write("        \">\r\n");
      out.write("      <div class=\"mask\" style=\"background-color: rgba(250, 182, 162, 0.15);\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Intro -->\r\n");
      out.write("  </section>\r\n");
      out.write("  <!--Section: Design Block-->\r\n");
      out.write("</header>\r\n");
      out.write("	<div class=\"container mt-5\" id =\"InterpreterDiv\">\r\n");
      out.write("		<h1>Espace Administrateur.</h1>\r\n");
      out.write("		<form id=\"interpreter-form\" action=\"interpreter\">\r\n");
      out.write("			<div class=\"form-group d-flex\">\r\n");
      out.write("  <label for=\"input\" class=\"mr-2 align-self-center\">Enter command:</label>\r\n");
      out.write("  <input type=\"text\" name=\"input\" id=\"input\" class=\"form-control mr-2 align-self-center\">\r\n");
      out.write("  <button type=\"submit\" class=\"btn btn-primary align-self-center\">Submit</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("		</form>\r\n");
      out.write("		<div id=\"result\" class=\"mt-3\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<!-- Include jQuery and Bootstrap JS -->\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("	<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("		// Submit form data using AJAX\r\n");
      out.write("		$('#interpreter-form').submit(function(event) {\r\n");
      out.write("			event.preventDefault(); // Prevent page refresh on form submission\r\n");
      out.write("			var form = $(this);\r\n");
      out.write("			var url = form.attr('action');\r\n");
      out.write("			const now = new Date();\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type: 'GET',\r\n");
      out.write("				url: url,\r\n");
      out.write("				data: form.serialize(), // Serialize form data for submission\r\n");
      out.write("				success: function(result) {\r\n");
      out.write("					var result2= result.split(\"\\n\");\r\n");
      out.write("					Swal.fire({\r\n");
      out.write("						  title:result2[0],\r\n");
      out.write("						  text: result2[1],\r\n");
      out.write("						  icon: result2[2],\r\n");
      out.write("						  confirmButtonText: 'OK'\r\n");
      out.write("						});\r\n");
      out.write("					now.setHours(now.getHours() + 1);\r\n");
      out.write("				    $('#result').append('<p>'+now.toLocaleTimeString()+':' + result2[2] + '</p>'); // Append result to #result div\r\n");
      out.write("\r\n");
      out.write("				    var resultDiv = document.getElementById(\"result\");\r\n");
      out.write("				    resultDiv.scrollTop = resultDiv.scrollHeight; // Scroll to bottom of #result div\r\n");
      out.write("				},\r\n");
      out.write("				error: function() {\r\n");
      out.write("					alert('Error submitting form!'); \r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
